name: build for windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make basic build
      run: make
    - name: cleanup
      run: make clean
    - name: make release build
      run: make release
